Improve compilation helper scripts

diff --git a/snapgear-2.6-p42/mi b/snapgear-2.6-p42/mi
--- a/snapgear-2.6-p42/mi
+++ b/snapgear-2.6-p42/mi
@@ -1,5 +1,18 @@
-# Clean, Compile, Create image.bin
+#!/bin/bash
+
+# delete old objects if present
 ./clean_ceidCam
-make
-./make_bin
-echo "make_bin: image.bin created succesfully!\n"
+
+# compile new image and create binary image for uploading
+make 
+if [ $? -eq 0 ]
+then
+	./make_bin
+	if [ $? -eq 0 ]
+	then
+		cat make_bin
+		echo "images/image.bin created succesfully!"
+	else
+		echo "ERROR: images/image.bin was not created! Check error above."
+	fi
+fi
